SET ANSI_NULLS ON 
GO 
SET QUOTED_IDENTIFIER ON 
GO 
SET ANSI_PADDING ON 
GO

CREATE TABLE [dbo].[EmployeeInfo]( 
    [EmpNo] [int] IDENTITY(1,1) NOT NULL, 
    [EmpName] [varchar](50) NOT NULL, 
    [Salary] [decimal](18, 0) NOT NULL, 
    [DeptName] [varchar](50) NOT NULL, 
    [Designation] [varchar](50) NOT NULL, 
	CONSTRAINT [PK_EmployeeInfo] PRIMARY KEY CLUSTERED 
	( 
		[EmpNo] ASC 
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO

SET ANSI_PADDING OFF 
GO